import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LandingPage from "@/components/landingpage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/muq4qgc.css" />  
      </head>
      <body className="font-adobe-garamond-pro">
        {children} 
      </body>
    </html>
  );
}
